### ISSUE TITLE
[INCIDENT][MOC-ZERO/ODH-KAFKA] - Kafka pods crashing

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#246]
Hello Operate First users,

We are investigating an ongoing incident affecting ODH Kafka on MOC-ZERO cluster.

Impacted users: All ODH Kafka users on the MOC Zero clsuter

We will provide updates to this issue thread as the incident progresses.

**Comment by HumairAK** [comment]
Seeing pvc full alerts: 
```
PVC data-odh-message-bus-kafka-2 utilization has crossed 85%. Free up some space or expand the PVC immediately.
```

**Comment by HumairAK** [comment]
Logs from opf-kafka `odh-message-bus-kafka-0` pod: 
<details>
<summary> pod logs </summary>
2021-04-09 18:11:08,509 INFO [SocketServer brokerId=0] Failed authentication with /10.131.0.39 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION-9091)-SSL-2]
2021-04-09 18:11:09,191 INFO [SocketServer brokerId=0] Failed authentication with /10.131.0.39 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION-9091)-SSL-0]
2021-04-09 18:11:09,229 INFO [SocketServer brokerId=0] Failed authentication with /10.131.0.39 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION-9091)-SSL-1]
2021-04-09 18:11:09,237 ERROR Error while writing to checkpoint file /var/lib/kafka/data/kafka-log0/__consumer_offsets-13/leader-epoch-checkpoint (kafka.server.LogDirFailureChannel) [ReplicaFetcherThread-0-2]
java.io.IOException: Disk quota exceeded
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:66)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.LeaderEpochCheckpointFile.write(LeaderEpochCheckpointFile.scala:62)
	at kafka.server.epoch.LeaderEpochFileCache.flush(LeaderEpochFileCache.scala:237)
	at kafka.server.epoch.LeaderEpochFileCache.$anonfun$assign$1(LeaderEpochFileCache.scala:66)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.utils.CoreUtils$.inWriteLock(CoreUtils.scala:261)
	at kafka.server.epoch.LeaderEpochFileCache.assign(LeaderEpochFileCache.scala:56)
	at kafka.log.Log.$anonfun$maybeAssignEpochStartOffset$1(Log.scala:1207)
	at kafka.log.Log.$anonfun$maybeAssignEpochStartOffset$1$adapted(Log.scala:1206)
	at scala.Option.foreach(Option.scala:407)
	at kafka.log.Log.maybeAssignEpochStartOffset(Log.scala:1206)
	at kafka.log.Log.$anonfun$append$6(Log.scala:1120)
	at kafka.log.Log.$anonfun$append$6$adapted(Log.scala:1118)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at kafka.log.Log.$anonfun$append$2(Log.scala:1118)
	at kafka.log.Log.maybeHandleIOException(Log.scala:2316)
	at kafka.log.Log.append(Log.scala:1032)
	at kafka.log.Log.appendAsFollower(Log.scala:1012)
	at kafka.cluster.Partition.$anonfun$doAppendRecordsToFollowerOrFutureReplica$1(Partition.scala:910)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:259)
	at kafka.cluster.Partition.doAppendRecordsToFollowerOrFutureReplica(Partition.scala:903)
	at kafka.cluster.Partition.appendRecordsToFollowerOrFutureReplica(Partition.scala:917)
	at kafka.server.ReplicaFetcherThread.processPartitionData(ReplicaFetcherThread.scala:161)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$7(AbstractFetcherThread.scala:317)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6(AbstractFetcherThread.scala:306)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6$adapted(AbstractFetcherThread.scala:305)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$5(AbstractFetcherThread.scala:305)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:305)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
2021-04-09 18:11:09,238 INFO [ReplicaManager broker=0] Stopping serving replicas in dir /var/lib/kafka/data/kafka-log0 (kafka.server.ReplicaManager) [LogDirFailureHandler]
2021-04-09 18:11:09,239 ERROR [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Error while processing data for partition __consumer_offsets-13 at offset 18075 (kafka.server.ReplicaFetcherThread) [ReplicaFetcherThread-0-2]
org.apache.kafka.common.errors.KafkaStorageException: Error while writing to checkpoint file /var/lib/kafka/data/kafka-log0/__consumer_offsets-13/leader-epoch-checkpoint
Caused by: java.io.IOException: Disk quota exceeded
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
	at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:257)
	at kafka.server.checkpoints.CheckpointFile.liftedTree1$1(CheckpointFile.scala:66)
	at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:50)
	at kafka.server.checkpoints.LeaderEpochCheckpointFile.write(LeaderEpochCheckpointFile.scala:62)
	at kafka.server.epoch.LeaderEpochFileCache.flush(LeaderEpochFileCache.scala:237)
	at kafka.server.epoch.LeaderEpochFileCache.$anonfun$assign$1(LeaderEpochFileCache.scala:66)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.utils.CoreUtils$.inWriteLock(CoreUtils.scala:261)
	at kafka.server.epoch.LeaderEpochFileCache.assign(LeaderEpochFileCache.scala:56)
	at kafka.log.Log.$anonfun$maybeAssignEpochStartOffset$1(Log.scala:1207)
	at kafka.log.Log.$anonfun$maybeAssignEpochStartOffset$1$adapted(Log.scala:1206)
	at scala.Option.foreach(Option.scala:407)
	at kafka.log.Log.maybeAssignEpochStartOffset(Log.scala:1206)
	at kafka.log.Log.$anonfun$append$6(Log.scala:1120)
	at kafka.log.Log.$anonfun$append$6$adapted(Log.scala:1118)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at kafka.log.Log.$anonfun$append$2(Log.scala:1118)
	at kafka.log.Log.maybeHandleIOException(Log.scala:2316)
	at kafka.log.Log.append(Log.scala:1032)
	at kafka.log.Log.appendAsFollower(Log.scala:1012)
	at kafka.cluster.Partition.$anonfun$doAppendRecordsToFollowerOrFutureReplica$1(Partition.scala:910)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:259)
	at kafka.cluster.Partition.doAppendRecordsToFollowerOrFutureReplica(Partition.scala:903)
	at kafka.cluster.Partition.appendRecordsToFollowerOrFutureReplica(Partition.scala:917)
	at kafka.server.ReplicaFetcherThread.processPartitionData(ReplicaFetcherThread.scala:161)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$7(AbstractFetcherThread.scala:317)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6(AbstractFetcherThread.scala:306)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$6$adapted(AbstractFetcherThread.scala:305)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at kafka.server.AbstractFetcherThread.$anonfun$processFetchRequest$5(AbstractFetcherThread.scala:305)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:305)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:133)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3$adapted(AbstractFetcherThread.scala:132)
	at scala.Option.foreach(Option.scala:407)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:132)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:114)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
2021-04-09 18:11:09,240 WARN [ReplicaFetcher replicaId=0, leaderId=2, fetcherId=0] Partition __consumer_offsets-13 marked as failed (kafka.server.ReplicaFetcherThread) [ReplicaFetcherThread-0-2]
2021-04-09 18:11:09,247 INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions Set(__consumer_offsets-22, zero-prod.thoth.package-update.hash-mismatch-0, __consumer_offsets-30, zero-prod.cluster.app-logs-1, zero-prod.thoth.inspection-completed-0, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, decoded-speech-0, zero-test.thoth.investigator.si-unanalyzed-package-0, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, zero-prod.thoth.advise-reporter.advise-justification-0, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, zero-prod.thoth.build-analysis-trigger-0, zero-prod.thoth.cve-update.cve-provided-0, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, zero-test.thoth.investigator.unresolved-pac...
2021-04-09 18:11:09,247 INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions Set(__consumer_offsets-22, zero-prod.thoth.package-update.hash-mismatch-0, __consumer_offsets-30, zero-prod.cluster.app-logs-1, zero-prod.thoth.inspection-completed-0, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, decoded-speech-0, zero-test.thoth.investigator.si-unanalyzed-package-0, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, zero-prod.thoth.advise-reporter.advise-justification-0, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, zero-prod.thoth.build-analysis-trigger-0, zero-prod.thoth.cve-update.cve-provided-0, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-37, zero-test.thoth.investigator.unresolve...
2021-04-09 18:11:09,285 INFO [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-22,zero-prod.thoth.package-update.hash-mismatch-0,__consumer_offsets-30,zero-prod.cluster.app-logs-1,zero-prod.thoth.inspection-completed-0,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,__consumer_offsets-46,decoded-speech-0,zero-test.thoth.investigator.si-unanalyzed-package-0,__consumer_offsets-25,__consumer_offsets-35,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,zero-prod.thoth.advise-reporter.advise-justification-0,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,zero-prod.thoth.build-analysis-trigger-0,zero-prod.thoth.cve-update.cve-provided-0,__consumer_offsets-42,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-37,zero-test.thoth.investigator.unresolved-package-0,__consumer_offsets-15,__consum...
2021-04-09 18:11:09,285 INFO Stopping serving logs in dir /var/lib/kafka/data/kafka-log0 (kafka.log.LogManager) [LogDirFailureHandler]
2021-04-09 18:11:09,289 ERROR Shutdown broker because all log dirs in /var/lib/kafka/data/kafka-log0 have failed (kafka.log.LogManager) [LogDirFailureHandler]
</details>

**Comment by HumairAK** [comment]
PVCs were resized

**Comment by HumairAK** [comment]
Restarting message-bus pods

**Comment by HumairAK** [comment]
Messages are confirmed flowing again.

**Comment by HumairAK** [comment]
This incident has been resolved.

Please let us know if you continue to see any remaining issues.

**Comment by 4n4nd** [comment]
Storage full again, new PR to increase storage
https://github.com/operate-first/apps/pull/513

**Comment by 4n4nd** [comment]
PVCs were expanded. Incident is resolved.
