### ISSUE TITLE
[Incident][MOC Zero] Noobaa endpoint unresponsive

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#347]
We're unable to pull data from noobaa via external connection.

Related: https://github.com/operate-first/support/issues/284

```
[32mJun-23 14:21:28.637[35m [Endpoint/13] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv object_api.read_object_md reqid 1729840@fcall://fcall(1mxaukot) connid fcall://fcall(1mxaukot) Error: No such object: obj_id undefined bucket SENSITIVE-135207161f2add25 key pr-logs/pull/operate-first_apps/787/kustomize-build/1407688976071921664/started.json
    at check_object_mode (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1491:15)
    at find_object_md (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1413:5)
    at async Object.read_object_md (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:771:17)
[32mJun-23 14:21:28.638[35m [Endpoint/13] [31m[ERROR][39m core.rpc.rpc:: RPC._request: response ERROR srv object_api.read_object_md params { bucket: SENSITIVE-135207161f2add25, key: [32m'pr-logs/pull/operate-first_apps/787/kustomize-build/1407688976071921664/started.json'[39m, version_id: [90mundefined[39m, md_conditions: [90mundefined[39m, encryption: [90mundefined[39m } reqid 1729840@fcall://fcall(1mxaukot) took [2.3+0.4=2.8] Error: No such object: obj_id undefined bucket SENSITIVE-135207161f2add25 key pr-logs/pull/operate-first_apps/787/kustomize-build/1407688976071921664/started.json
    at RpcRequest._set_response (/root/node_modules/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/root/node_modules/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/root/node_modules/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcFcallConnection.<anonymous> (/root/node_modules/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcFcallConnection.emit (events.js:314:20)
    at RpcFcallConnection.EventEmitter.emit (domain.js:483:12)
    at Immediate._onImmediate (/root/node_modules/noobaa-core/src/rpc/rpc_fcall.js:15:53)
    at processImmediate (internal/timers.js:461:21)
[32mJun-23 14:21:28.638[35m [Endpoint/13] [31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/pr-logs/pull/operate-first_apps/787/kustomize-build/1407688976071921664/started.json</Resource><RequestId>kq9kej7e-4lgrvw-u8w</RequestId></Error> GET /ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/pr-logs/pull/operate-first_apps/787/kustomize-build/1407688976071921664/started.json {"host":"s3.openshift-storage.svc.cluster.local","user-agent":"aws-sdk-go/1.31.12 (go1.16.2; linux; amd64)","authorization":"AWS4-HMAC-SHA256 Credential=mM8HzDK82lqAtKapmwca/20210623/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=37d99b9eb660f648e77a22643aded5b7dd40a04fe1ed8b855e7cdb10a45f7fc2","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","x-amz-date":"202...
    at RpcRequest._set_response (/root/node_modules/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/root/node_modules/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/root/node_modules/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcFcallConnection.<anonymous> (/root/node_modules/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcFcallConnection.emit (events.js:314:20)
    at RpcFcallConnection.EventEmitter.emit (domain.js:483:12)
    at Immediate._onImmediate (/root/node_modules/noobaa-core/src/rpc/rpc_fcall.js:15:53)
    at processImmediate (internal/timers.js:461:21)
[32mJun-23 14:21:30.037[35m [Endpoint/13] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv object_api.read_object_md reqid 1729842@fcall://fcall(1mxaukot) connid fcall://fcall(1mxaukot) Error: No such object: obj_id undefined bucket SENSITIVE-135207161f2add25 key pr-logs/pull/thoth-station_thoth-application/1758/pre-commit/1407660443996000256/started.json
    at check_object_mode (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1491:15)
    at find_object_md (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1413:5)
    at async Object.read_object_md (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:771:17)
[32mJun-23 14:21:30.038[35m [Endpoint/13] [31m[ERROR][39m core.rpc.rpc:: RPC._request: response ERROR srv object_api.read_object_md params { bucket: SENSITIVE-135207161f2add25, key: [32m'pr-logs/pull/thoth-station_thoth-application/1758/pre-commit/1407660443996000256/started.json'[39m, version_id: [90mundefined[39m, md_conditions: [90mundefined[39m, encryption: [90mundefined[39m } reqid 1729842@fcall://fcall(1mxaukot) took [2.3+0.4=2.7] Error: No such object: obj_id undefined bucket SENSITIVE-135207161f2add25 key pr-logs/pull/thoth-station_thoth-application/1758/pre-commit/1407660443996000256/started.json
    at RpcRequest._set_response (/root/node_modules/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/root/node_modules/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/root/node_modules/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcFcallConnection.<anonymous> (/root/node_modules/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcFcallConnection.emit (events.js:314:20)
    at RpcFcallConnection.EventEmitter.emit (domain.js:483:12)
    at Immediate._onImmediate (/root/node_modules/noobaa-core/src/rpc/rpc_fcall.js:15:53)
    at processImmediate (internal/timers.js:461:21)
[32mJun-23 14:21:30.038[35m [Endpoint/13] [31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/pr-logs/pull/thoth-station_thoth-application/1758/pre-commit/1407660443996000256/started.json</Resource><RequestId>kq9kekaa-b7iaa8-11u9</RequestId></Error> GET /ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/pr-logs/pull/thoth-station_thoth-application/1758/pre-commit/1407660443996000256/started.json {"host":"s3.openshift-storage.svc.cluster.local","user-agent":"aws-sdk-go/1.31.12 (go1.16.2; linux; amd64)","authorization":"AWS4-HMAC-SHA256 Credential=mM8HzDK82lqAtKapmwca/20210623/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b820badf26e9f592b5b092bcd6e16eb4ea6b884e8b8754e79ba64ac532fe6092","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855...
    at RpcRequest._set_response (/root/node_modules/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/root/node_modules/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/root/node_modules/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcFcallConnection.<anonymous> (/root/node_modules/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcFcallConnection.emit (events.js:314:20)
    at RpcFcallConnection.EventEmitter.emit (domain.js:483:12)
    at Immediate._onImmediate (/root/node_modules/noobaa-core/src/rpc/rpc_fcall.js:15:53)
    at processImmediate (internal/timers.js:461:21)

[32mJun-23 14:21:42.137[35m [Endpoint/13] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv object_api.read_object_md reqid 1729853@fcall://fcall(1mxaukot) connid fcall://fcall(1mxaukot) Error: No such object: obj_id undefined bucket SENSITIVE-135207161f2add25 key pr-logs/pull/operate-first_apps/788/kustomize-build/1407676748887232512/started.json
    at check_object_mode (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1491:15)
    at find_object_md (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:1413:5)
    at async Object.read_object_md (/root/node_modules/noobaa-core/src/server/object_services/object_server.js:771:17)
[32mJun-23 14:21:42.137[35m [Endpoint/13] [31m[ERROR][39m core.rpc.rpc:: RPC._request: response ERROR srv object_api.read_object_md params { bucket: SENSITIVE-135207161f2add25, key: [32m'pr-logs/pull/operate-first_apps/788/kustomize-build/1407676748887232512/started.json'[39m, version_id: [90mundefined[39m, md_conditions: [90mundefined[39m, encryption: [90mundefined[39m } reqid 1729853@fcall://fcall(1mxaukot) took [2.3+0.4=2.7] Error: No such object: obj_id undefined bucket SENSITIVE-135207161f2add25 key pr-logs/pull/operate-first_apps/788/kustomize-build/1407676748887232512/started.json
    at RpcRequest._set_response (/root/node_modules/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/root/node_modules/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/root/node_modules/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcFcallConnection.<anonymous> (/root/node_modules/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcFcallConnection.emit (events.js:314:20)
    at RpcFcallConnection.EventEmitter.emit (domain.js:483:12)
    at Immediate._onImmediate (/root/node_modules/noobaa-core/src/rpc/rpc_fcall.js:15:53)
    at processImmediate (internal/timers.js:461:21)
[32mJun-23 14:21:42.137[35m [Endpoint/13] [31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/pr-logs/pull/operate-first_apps/788/kustomize-build/1407676748887232512/started.json</Resource><RequestId>kq9ketmd-cuqcyz-9p0</RequestId></Error> GET /ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/pr-logs/pull/operate-first_apps/788/kustomize-build/1407676748887232512/started.json {"host":"s3.openshift-storage.svc.cluster.local","user-agent":"aws-sdk-go/1.31.12 (go1.16.2; linux; amd64)","authorization":"AWS4-HMAC-SHA256 Credential=mM8HzDK82lqAtKapmwca/20210623/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b82dbf8a8fbccb03e5425df25b4bed92f697cf86f517dff355dac90ea187b121","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","x-amz-date":"202...
    at RpcRequest._set_response (/root/node_modules/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/root/node_modules/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/root/node_modules/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcFcallConnection.<anonymous> (/root/node_modules/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcFcallConnection.emit (events.js:314:20)
    at RpcFcallConnection.EventEmitter.emit (domain.js:483:12)
    at Immediate._onImmediate (/root/node_modules/noobaa-core/src/rpc/rpc_fcall.js:15:53)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by tumido** [comment]
![image](https://user-images.githubusercontent.com/7453394/123118933-5cd08980-d443-11eb-9127-88b197271601.png)

Noobaa sees to be erroring but Ceph is reporting healthy:

```
Error EINVAL: invalid command
sh-4.4# ceph status
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum e,g,h (age 5d)
    mgr: a(active, since 5d)
    mds: ocs-storagecluster-cephfilesystem:1 {0=ocs-storagecluster-cephfilesystem-a=up:active} 1 up:standby-replay
    osd: 9 osds: 9 up (since 5d), 9 in (since 8w)
    rgw: 2 daemons active (ocs.storagecluster.cephobjectstore.a, ocs.storagecluster.cephobjectstore.b)

  task status:
    scrub status:
        mds.ocs-storagecluster-cephfilesystem-a: idle
        mds.ocs-storagecluster-cephfilesystem-b: idle

  data:
    pools:   10 pools, 464 pgs
    objects: 1.63M objects, 947 GiB
    usage:   3.0 TiB used, 1.9 TiB / 4.9 TiB avail
    pgs:     464 active+clean

  io:
    client:   15 MiB/s rd, 21 MiB/s wr, 19 op/s rd, 38 op/s wr
```

**Comment by tumido** [comment]
Noobaa core seems to have networking troubles:

```
[32mJun-23 14:48:51.197[35m [WebServer/35] [36m   [L0][39m core.rpc.ice:: Got error Error: connect ECONNREFUSED 192.12.185.130:60100
[90m    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)[39m {
  errno: [32m'ECONNREFUSED'[39m,
  code: [32m'ECONNREFUSED'[39m,
  syscall: [32m'connect'[39m,
  address: [32m'192.12.185.130'[39m,
  port: [33m60100[39m
}
[32mJun-23 14:48:51.208[35m [WebServer/35] [36m   [L0][39m core.rpc.ice:: Got error Error: connect ECONNREFUSED 192.12.185.130:60100
[90m    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)[39m {
  errno: [32m'ECONNREFUSED'[39m,
  code: [32m'ECONNREFUSED'[39m,
  syscall: [32m'connect'[39m,
  address: [32m'192.12.185.130'[39m,
  port: [33m60100[39m
}
```

**Comment by tumido** [comment]
This issue seems to be blocking Prow in completing CI runs

**Comment by tumido** [comment]
I'll try restarting noobaa

**Comment by tumido** [comment]
Noobaa core is still logging:

```
[32mJun-23 16:50:56.090[35m [WebServer/722] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv system_api.read_system reqid 12@wss://noobaa-mgmt-openshift-storage.apps.zero.massopen.cloud(nxdrpozj.zz) connid ws://[::ffff:10.129.6.1]:36802/(16qtesjia) Error: RPC CONN NOT CONNECTED closed ws://[::ffff:10.129.6.1]:36802/(16qtesjia)
    at RpcWsConnection.send (/root/node_modules/noobaa-core/src/rpc/rpc_base_conn.js:107:19)
    at /root/node_modules/noobaa-core/src/rpc/rpc.js:381:29
    at tryCatcher (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:559:17)
[32mJun-23 16:50:56.093[35m [WebServer/722] [33m [WARN][39m core.rpc.rpc:: RPC._on_message: ERROR from _on_request Error: RPC CONN NOT CONNECTED closed ws://[::ffff:10.129.6.1]:36802/(16qtesjia)
    at RpcWsConnection.send (/root/node_modules/noobaa-core/src/rpc/rpc_base_conn.js:107:19)
    at /root/node_modules/noobaa-core/src/rpc/rpc.js:400:29
    at tryCatcher (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by HumairAK** [comment]
To reproduce some of the recurring issues: 

1. Create or use an existing Nooba bucket, with some data in it
2. try to pull the data, or store data via an s3 cli (I used s3cmd), it should timeout

**Comment by larsks** [comment]
I've opened a sev 2 case @ https://access.redhat.com/support/cases/#/case/02972192

**Comment by harshad16** [comment]
Having issue in write operation as well 
`Failed to put file: Put http://s3.openshift-storage.svc.cluster.local/thoth/data/zero-prod/solver/solver-fedora-34-py39-210624201919-6e1da0efa6e42c80: net/http: timeout awaiting response headers`

**Comment by fridex** [comment]
Also, browsing the content does not look operational now:

```
An error occurred (504) when calling the ListObjectsV2 operation (reached max retries: 4): Gateway Timeout
```

**Comment by 4n4nd** [comment]
This issue seems to have resolved itself after @larsks restarted one of the nodes (`os-wrk-1`).
